id: rhcs-travel-agency
title: Cloud JBoss BPM Travel Agency Demo
github_repo_url: https://github.com/redhatdemocentral/rhcs-travel-agency-demo
technologies:
  - Red Hat CDK
  - JBoss BPM Suite
  - OpenShift Enterprise  
summary: Project to automate the installation of JBoss BPM Travel Agency using the Red Hat Container Development Kit (CDK) for application development activities on OpenShift.
level: Beginner
product: rhcs
author: Niraj Patel, Shepherd Chengeta, Andrew Block, Eric D. Schabell
